services:
  ical:
    build: ical_service/
    container_name: ICALService
    ports:
      - "3000:3000"
    networks:
      - calendar_network
    environment:
      TZ: Europe/London

  calendar:
    build: calendar_service/
    container_name: CalendarService
    depends_on:
      - ical
    networks:
      - calendar_network
    environment:
      TZ: Europe/London

networks:
  calendar_network:
    driver: bridge
